export const dummyColumnNames = [
  "Desserts",
  "Calories",
  "Fat (g)",
  "Carbs (g)",
  "Protein (g)",
];

export const dummyTableRows = [
  {
    rowName: "Frozen yoghurt",
    calories: 159,
    fat: 6.0,
    carbs: 24,
    protein: 4.0,
  },
  {
    rowName: "Ice cream sandwich",
    calories: 237,
    fat: 9.0,
    carbs: 37,
    protein: 4.3,
  },
  {
    rowName: "Eclair",
    calories: 262,
    fat: 16.0,
    carbs: 24,
    protein: 6.0,
  },
  {
    rowName: "Cupcake",
    calories: 305,
    fat: 3.7,
    carbs: 67,
    protein: 4.3,
  },
  {
    rowName: "Gingerbread",
    calories: 356,
    fat: 16,
    carbs: 49,
    protein: 3.9,
  },
  {
    rowName: "Honeycomb",
    calories: 408,
    fat: 3.2,
    carbs: 87,
    protein: 6.5,
  },

  {
    rowName: "Jelly Bean",
    calories: 375,
    fat: 0,
    carbs: 94,
    protein: 0,
  },
  {
    rowName: "KitKat",
    calories: 518,
    fat: 26,
    carbs: 65,
    protein: 7,
  },
  {
    rowName: "Lollipop",
    calories: 392,
    fat: 0.2,
    carbs: 98,
    protein: 0,
  },
  {
    rowName: "Marshmallow",
    calories: 318,
    fat: 0,
    carbs: 81,
    protein: 2,
  },
  {
    rowName: "Nougat",
    calories: 360,
    fat: 16,
    carbs: 49,
    protein: 3.9,
  },
  {
    rowName: "Oreo",
    calories: 437,
    fat: 18,
    carbs: 63,
    protein: 4,
  },
];
